module.exports = {
  docs: {
    "Console Table Printer": [
      "doc-install-quick-start",
      "doc-table-instance-creation",
      "doc-adding-rows",
      "doc-row-divider",
      "doc-add-columns",
      "doc-color",
      "doc-no-ascii",
      "doc-sort-filter",
      "doc-alignment",
      "doc-enable-disable-col",
      "doc-computed-function",
      "doc-title",
      "doc-column-title",
      "doc-limit-line-width",
      "doc-border-design",
      "doc-emojis-special-chars",
      "doc-render-console",
      "doc-typescript",
    ],
    "Table Printer CLI": ["doc-cli-install-quick-start"],
  },
};
